menu:
  首页: /
  归档: /archives
  书单: /books
  关于: /about


widgets:
- category
- tagcloud
- recent_posts
- links

post_widgets:
- toc


#- duoshuo_recent_comments


excerpt_link: Read More  |  详情

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

links: 
- name: MZZO
  link: http://www.mzzo.net/
- name: 一只猿
  link: http://92ez.com/
- name: Lellansin's 冰森
  link: http://www.lellansin.com/ 
- name: HDH的Blog
  link: http://www.hdher.com/ 


cnzz: true

#comment_provider: facebook
# Facebook comment
#facebook:
#  appid: 123456789012345
#  comment_count: 5
#  comment_width: 840
#  comment_colorscheme: light
